<?php

// autoload_psr4.php @generated by Niko

$baseDir = '../librariesExternals/';

// Adding Namespaces to external libraries automatically
foreach ($autoload_src as $src_vendor) {

    $librariesDir = $baseDir . $src_vendor . '/';

    $composer = file_get_contents( $librariesDir . 'composer.json');
    $composer_autoload = json_decode($composer)->autoload;

    foreach ($composer_autoload as $type => $paths) {
        if ($type === 'psr-4') {
            foreach ($paths as $namespace => $path) {
                $path = $librariesDir . $path;
                $map_librariesExternals[$namespace] = $path;
            }
        }
    }
}
// Mes namespaces
// Adding Custom Namespaces automatically
$map_custom = json_decode($config,true)['autoload'];

// Merge array
$map = array_merge($map_librariesExternals,$map_custom);

return $map;
