<?php

// autoload_files.php @generated by Niko

$baseDir = "../librariesExternals/";

// Adding Require Files to external libraries automatically
foreach ($autoload_src as $src_vendor) {

    $librariesDir = $baseDir . $src_vendor . '/';
    $basePath = dirname(dirname(dirname(__DIR__))) . substr($librariesDir,2);  

    $composer = file_get_contents( $librariesDir . 'composer.json');
    $composer_autoload = json_decode($composer)->autoload;

    foreach ($composer_autoload as $type => $paths) {
        if ($type === 'files') {
            foreach ($paths as $namespace => $path) {
                $path = $basePath . $path;
                $includeFiles_librariesExternals[] = $path;
            }
        }
    }
}
// Adding Custom Require Files automatically
$includeFiles_custom = json_decode($config,true)['files'];
// Fusion des tableaux
$includeFiles = array_merge($includeFiles_librariesExternals,$includeFiles_custom);

return $includeFiles;