<?php

// autoload_psr4.php @generated by Niko

// Find 'config.json' and search paths to externals librairies
$config = file_get_contents('../config/autoload.json'); 
return json_decode($config)->librariesExternals;
